feat: ✨ social-auth auto associate existing user
hacktoolkit/django-htk pull request #458
Opened 2024-12-13 21:08 UTC by goztrk

## Description
Allows desired social auth backends to be defined as auto-associate. This will allow to associate social accounts with existing accounts in the pipeline automatically.

2024-12-13 21:11 UTC, goztrk commented on apps/accounts/social_auth_pipeline.py
## Reviewer's Note
Most of this is formatting. The important part is marked with a comment.

2024-12-13 21:11 UTC, goztrk commented on apps/accounts/social_auth_pipeline.py
> +                    associate_user(backend, uid, user=user)
## Reviewer's Note
The main change!

2024-12-15 12:10 UTC, jontsai requested changes

2024-12-15 12:10 UTC, jontsai commented on apps/accounts/social_auth_pipeline.py
> +                    # must happen in here.
This makes sense. Could we expand this command and include the reasoning `why` ?

"... must happen in here because ..."

2024-12-16 11:46 UTC, jontsai approved these changes
LGTM

2024-12-16 11:46 UTC, merged